[build-system]
requires = ["setuptools","pyarrow===14.0.1","pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "lingodb-bridge"
version = "0.0.1"
dependencies = [
    "pyarrow===14.0.1"
]