name: Release Build for WebInterface

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'git ref to build'
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/lingo-db/lingodb-py-dev:16387d412a5824bad8031811bebc136b1cd6da1f

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: ${{ inputs.ref }}
      - name: Build
        run: |
          export PATH=/built-llvm/bin/:$PATH
          mkdir build
          cmake -G Ninja . -B build -DCMAKE_BUILD_TYPE=Release -DClang_DIR=/built-llvm/lib/cmake/clang -DArrow_DIR=/built-arrow/lib64/cmake/Arrow -DArrowCompute_DIR=/built-arrow/lib64/cmake/ArrowCompute -DENABLE_TESTS=OFF -DENABLE_BASELINE_BACKEND=True
          cmake --build build
      - uses: actions/upload-artifact@master
        with:
          name: release-build
          path: build
          retention-days: 1
